controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rear_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    front_steering_position_controller:
      type: position_controllers/JointGroupPositionController


joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true


rear_wheel_velocity_controller:
  ros__parameters:
    joints:
      - base_leftBack_wheel_joint
      - base_rightBack_wheel_joint
    interface_name: velocity


front_steering_position_controller:
  ros__parameters:
    joints:
      - base_leftFront_steer_joint
      - base_rightFront_steer_joint
    interface_name: position